Russian translation
owntracks/android pull request #855
Opened 2020-09-29 10:54 UTC by Allineer

values-ru/strings.xml

2020-09-29 12:02 UTC, evgeni commented on project/app/src/main/res/values-ru/strings.xml
> +    <string name="importConfig">Испорт</string>
```suggestion
    <string name="importConfig">Импорт</string>
```

2020-09-29 12:02 UTC, evgeni commented on project/app/src/main/res/values-ru/strings.xml
> +    <string name="transitionEntering">прибыла(а) в</string>
```suggestion
    <string name="transitionEntering">прибыл(а) в</string>
```

2020-09-29 12:37 UTC, Allineer commented
@evgeni, спасибо!

2020-09-29 12:44 UTC, jpmens commented
@Allineer thank you very much for your contribution! As I cannot read Russian, unfortunately, I asked @evgeni to double-check. So thank you both.

2020-09-29 13:32 UTC, hostmaster requested changes

2020-09-29 13:32 UTC, hostmaster commented on project/app/src/main/res/values-ru/strings.xml
> +    <string name="preferencesRemoteCommandSummary">Расрешить внешние команды</string>
```suggestion
    <string name="preferencesRemoteCommandSummary">Разрешить внешние команды</string>
```

2020-09-29 13:32 UTC, hostmaster commented on project/app/src/main/res/values-ru/strings.xml
> +    <string name="addWaypoint">Места</string>
```suggestion
    <string name="addWaypoint">Добавить местоположение</string>
```

2020-09-29 13:32 UTC, hostmaster commented on project/app/src/main/res/values-ru/strings.xml
> +    <string name="preferencesIdentification">Индентификация</string>
```suggestion
    <string name="preferencesIdentification">Идентификация</string>
```

2020-09-29 13:32 UTC, hostmaster commented on project/app/src/main/res/values-ru/strings.xml
> +    <string name="permissions_description">Owntracks необходимо разрешение на определение вашего местоположения. Пожалуйста, предоставьте это разрешение, прежде чем продождить.</string>
```suggestion
    <string name="permissions_description">Owntracks необходимо разрешение на определение вашего местоположения. Пожалуйста, предоставьте это разрешение, прежде чем продолжить.</string>
```

2020-09-29 13:47 UTC, Allineer commented
@hostmaster, спасибо!

2020-09-29 13:50 UTC, Allineer commented on project/app/src/main/res/values-ru/strings.xml
> +    <string name="addWaypoint">Места</string>
Стоп. Waypoint - это все-таки не "местоположение". В этом переводе я использую аналогию с "Местами" в Life360 - это действительно описание конкретного места на карте, зоны, точки в которая может совпасть с нашим местоположением и тогда можно говорить о том, что мы вошли в эту точку или покинули ее.

Поэтому я исправлю на "Добавить место".

2020-09-30 14:47 UTC, growse commented
Thanks! Could you also update `project/app/build.gradle` L33 to add the correct resConfig? This will allow these translations to be built into the output.

(There's also a bug in the GH action which causes this to look like it's failed the build when it hasn't. Fix is on master. Please ignore).

2020-10-01 06:15 UTC, Allineer commented
@growse, is done

2020-10-19 11:26 UTC, growse commented
I've squashed these onto master manually - couldn't do manually as I've managed to completely re-do the gradle files in the meantime, so couldn't cleanly merge. Thanks!

2020-10-19 11:26 UTC, closed without merging

2021-03-15 09:29 UTC, Allineer commented
@growse FYI:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/1168049/111132039-f1486780-8589-11eb-9833-107f7078b324.png">